### ISSUE TITLE
Issue after update to 1.0.3

### ISSUE THREAD

**Issue by gogogorski** [HashandSalt/kirby3-twitter#10]
First of all, thanks for the great plugin. It worked perfectly for me till the recent update (plugin version 1.0.3).
I've updated everything via Composer and followed your instructions strictly, but I'm receiving the error message:

"Argument 2 passed to HashAndSalt\Twitter\Twitter::twitterCache() must be an instance of HashAndSalt\Twitter\mixed, array given, called in /site/plugins/kirby3-twitter/src/classes/Twitter.php on line 90"

Any ideas where this might come from?

**Comment by HashandSalt** [comment]
Thanks for reporting and for the nice words :) This is already on my radar, and has been reported here https://github.com/HashandSalt/kirby3-twitter/issues/9

I just need to find a few minutes to look into it, hopefully in the next day or so :(

**Comment by gogogorski** [comment]
Thanks for the quick answer. If that helps: I've changed the PHP version on my local MAMP server from 7.4.2 to 8.0 which seems to fix the problem.

**Comment by HashandSalt** [comment]
Yes im running 8 locally and cant reproduce it, thanks for the info.
