### ISSUE TITLE
Error in 'Usage' snippet from README

### ISSUE THREAD

**Issue by JoshApos** [HashandSalt/kirby3-twitter#6]
The following snippet (found in the 'Usage' section of the README file) was throwing a couple of errors when I tried using it:
`<?= snippet('twitter/tweets', ['type' => 'statuses/home_timeline', 'count' => 6, 'excludeReplies' => true, 'screenName' => null, 'media' => true])?>`

The issue appears to be with the `excludeReplies` and `screenName` variable names, which are written here in camelcase, but the plugin seems to expect them in full lowercase.

**Comment by HashandSalt** [comment]
This has been fixed :) 

Please reinstall the plugin. You will need to use camel casing after doing so.
