### ISSUE TITLE
Bundled TwitterOAuth library appears to be an outdated version

### ISSUE THREAD

**Issue by sebastiangreger** [HashandSalt/kirby3-twitter#8]
Could it be that the bundled files in `vendor/abraham/twitteroauth` (timestamped 7 months ago) do not yet reflect the recent update of dependencies?

cf. https://forum.getkirby.com/t/twit-plugin-twitter-feed-help/24183/15 (cc @JoshApos)

**Comment by HashandSalt** [comment]
This is solved on the dev branch.
